### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by puzzlewolf** [puzzlewolf/bluefate_website#24]
The default RSS feed includes all posts, e.g. the band member bios. Reduce it to concerts (and other news-y content, like new photo posts) only.

**Comment by puzzlewolf** [comment]
Also, we should have a visible link to the RSS feed somewhere.

**Comment by p3tr0sh** [comment]
The concerts-only rss-feed is visible at [https://www.bluefate.de/concerts/index.xml](https://www.bluefate.de/concerts/index.xml).

**Comment by p3tr0sh** [comment]
Think this should be done with https://github.com/puzzlewolf/bluefate_website/commit/e269531135b010c84cc61f875d67343f3fe9cc12
